package com.example.voiceassistant.ui.theme

import androidx.compose.ui.graphics.Color

// "Secure Tonal Interface" — Deep Teal seed. See DESIGN.md for the role table.

// --- Light ---
val LightPrimary = Color(0xFF004F52)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF00696D)
val LightOnPrimaryContainer = Color(0xFF96E5EA)
val LightSecondary = Color(0xFF4A6363)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E7)
val LightOnSecondaryContainer = Color(0xFF506969)
val LightTertiary = Color(0xFF334863)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF4B607C)
val LightOnTertiaryContainer = Color(0xFFC5DBFB)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightBackground = Color(0xFFF7FAF9)
val LightOnBackground = Color(0xFF181C1C)
val LightSurface = Color(0xFFF7FAF9)
val LightOnSurface = Color(0xFF181C1C)
val LightSurfaceVariant = Color(0xFFE0E3E3)
val LightOnSurfaceVariant = Color(0xFF3E4949)
val LightOutline = Color(0xFF6F7979)
val LightOutlineVariant = Color(0xFFBEC9C9)
val LightInverseSurface = Color(0xFF2D3131)
val LightInverseOnSurface = Color(0xFFEEF1F1)
val LightInversePrimary = Color(0xFF85D3D7)
val LightSurfaceTint = Color(0xFF00696D)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF1F4F4)
val LightSurfaceContainer = Color(0xFFEBEEEE)
val LightSurfaceContainerHigh = Color(0xFFE6E9E8)
val LightSurfaceContainerHighest = Color(0xFFE0E3E3)
val LightSurfaceDim = Color(0xFFD7DBDA)
val LightSurfaceBright = Color(0xFFF7FAF9)

// --- Dark (deep ink) ---
val DarkPrimary = Color(0xFF85D3D7)
val DarkOnPrimary = Color(0xFF00363A)
val DarkPrimaryContainer = Color(0xFF004F52)
val DarkOnPrimaryContainer = Color(0xFFA1F0F4)
val DarkSecondary = Color(0xFFB1CCCB)
val DarkOnSecondary = Color(0xFF1B3534)
val DarkSecondaryContainer = Color(0xFF324B4B)
val DarkOnSecondaryContainer = Color(0xFFCCE8E7)
val DarkTertiary = Color(0xFFB2C8E8)
val DarkOnTertiary = Color(0xFF1B3148)
val DarkTertiaryContainer = Color(0xFF334863)
val DarkOnTertiaryContainer = Color(0xFFD2E4FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF181C1C)
val DarkOnBackground = Color(0xFFE0E3E3)
val DarkSurface = Color(0xFF181C1C)
val DarkOnSurface = Color(0xFFE0E3E3)
val DarkSurfaceVariant = Color(0xFF3F4948)
val DarkOnSurfaceVariant = Color(0xFFBEC9C9)
val DarkOutline = Color(0xFF899392)
val DarkOutlineVariant = Color(0xFF3F4948)
val DarkInverseSurface = Color(0xFFE0E3E3)
val DarkInverseOnSurface = Color(0xFF2D3131)
val DarkInversePrimary = Color(0xFF00696D)
val DarkSurfaceTint = Color(0xFF85D3D7)
val DarkSurfaceContainerLowest = Color(0xFF0B0F0F)
val DarkSurfaceContainerLow = Color(0xFF181C1C)
val DarkSurfaceContainer = Color(0xFF1C2120)
val DarkSurfaceContainerHigh = Color(0xFF272B2B)
val DarkSurfaceContainerHighest = Color(0xFF313635)
val DarkSurfaceDim = Color(0xFF101414)
val DarkSurfaceBright = Color(0xFF3E4242)
